<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE BookCatalog [
	<!ELEMENT BookCatalog (Book*)>
	<!ELEMENT Book (Title, Author, Year, Price)>
	<!ELEMENT Title (#PCDATA)>
	<!ELEMENT Author (#PCDATA)>
	<!ELEMENT Year (#PCDATA)>
	<!ELEMENT Price (#PCDATA)>
	<!ATTLIST Book lang CDATA #IMPLIED>
	<!ATTLIST Book code ID #IMPLIED>
	<!ATTLIST Price unit (원 | 달러 | 엔) #REQUIRED>
]>
<BookCatalog>
    <Book code="내책1">
        <Title>개미</Title>
        <Author>베르나르베르베르</Author>
        <Year>1991</Year>
	<Price unit="원">25000</Price>
    </Book>
    <Book code="하이">
        <Title>나미야 잡화점의 기적</Title>
        <Author>히가시노 게이고</Author>
        <Year>2012</Year>
	<Price unit="달러">2.5</Price>
    </Book>
    <Book code="내책1">
        <Title>나는 너를 본다</Title>
        <Author>클레어맥킨토시</Author>
        <Year>2017</Year>
	<Price unit="엔">2500</Price>
    </Book>
</BookCatalog>
