<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE BookCatalog [
	<!ELEMENT BookCatalog (Book*)>
	<!ELEMENT Book (Title, Author, Year)>
	<!ELEMENT Title (#PCDATA)>
	<!ELEMENT Author (#PCDATA)>
	<!ELEMENT Year (#PCDATA)>
	<!ATTLIST Book lang CDATA #IMPLIED>
	<!ATTLIST Book code ID "내 책">
]>
<BookCatalog>
    <Book code="내책1">
        <Title>개미</Title>
        <Author>베르나르베르베르</Author>
        <Year>1991</Year>
    </Book>
    <Book code="하이">
        <Title>나미야 잡화점의 기적</Title>
        <Author>히가시노 게이고</Author>
        <Year>2012</Year>
	<Summary>좀도둑이 과거로부터 도착한 고민 상담 편지에 답장하며 겪게 되는 하룻밤 이야기</Summary>
    </Book>
    <Book code="내책1">
        <Title>나는 너를 본다</Title>
        <Author>클레어맥킨토시</Author>
        <Year>2017</Year>
	<Summary>마지막에 반전을 둔 스릴러 소설</Summary>
    </Book>
</BookCatalog>
