=== 9aeun/SKU/3학년/웹정보프레임워크/Exercise/Ex4-5.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
		targetNamespace="http://cs.skuniv.ac.kr/xml/gaeun"
		xmlns:target="http://cs.skuniv.ac.kr/xml/gaeun"
		elementFormDefault="qualified">
	<group name="AlbumGroup">
		<sequence>
			<element name="Title" type="string"/>
			<element name="Artist" type="string"/>
			<element name="Genre" type="string"/>
			<element name="Released-date" type="string"/>
			<element name="Song" type="string" maxOccurs="unbounded"/>
		</sequence>
	</group>

	<element name="AudioCatalog">
		<complexType>
			<choice  maxOccurs="unbounded">
				<element name="Cd">
					<complexType>
						<group ref="target:AlbumGroup" />
					</complexType>
				</element>
				<element name="Record">
					<complexType>
						<group ref="target:AlbumGroup" />
					</complexType>
				</element>
				<element name="MP3">
					<complexType>
						<group ref="target:AlbumGroup" />
					</complexType>
				</element>
			</choice>
		</complexType>
	</element>

</schema>

=== 9aeun/SKU/3학년/웹정보프레임워크/Exercise/Ex4-5.xml
<?xml version="1.0" encoding="utf-8"?>
<AudioCatalog xmlns="http://cs.skuniv.ac.kr/xml/gaeun"
	  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	  xsi:schemaLocation="http://cs.skuniv.ac.kr/xml/gaeun Ex4-5.xsd">

    <Cd>
        <Title> Attention </Title>
	<Artist> New Jeans </Artist>
	<Genre> Dance </Genre>
	<Released-date> 2022-08-01 </Released-date>
	<Song> Hype boy </Song>
	<Song> Cookie </Song>
	<Song> Hurt </Song>
    </Cd>

    <Record>
        <Title> Attention </Title>
	<Artist> New Jeans </Artist>
	<Genre> Dance </Genre>
	<Released-date> 2022-08-01 </Released-date>
	<Song> Hype boy </Song>
	<Song> Cookie </Song>
	<Song> Hurt </Song>
    </Record>

    <MP3>
        <Title> Attention </Title>
	<Artist> New Jeans </Artist>
	<Genre> Dance </Genre>
	<Released-date> 2022-08-01 </Released-date>
	<Song> Hype boy </Song>
	<Song> Cookie </Song>
	<Song> Hurt </Song>
    </MP3>
</AudioCatalog>
